/* eslint-disable */
/* prettier-ignore */

/**
 * Generated by @igniter-js/cli
 *
 * WARNING: DO NOT EDIT THIS FILE MANUALLY
 *
 * This file was automatically generated from your Igniter router.
 * Any changes made to this file will be overwritten when the CLI regenerates it.
 *
 * To modify the client API, update your controller files instead.
 *
 * Generated: 2025-09-26T20:06:34.930Z
 * Framework: nextjs
 * Output: src/
 */

// Generated by @igniter-js/cli - DO NOT EDIT

export const AppRouterSchema = {
  "controllers": {
    "example": {
      "name": "example",
      "path": "/example",
      "actions": {
        "hello": {
          "path": "/hello",
          "method": "GET",
          "$Infer": {}
        }
      }
    },
    "auth": {
      "name": "auth",
      "path": "/auth",
      "actions": {
        "signIn": {
          "type": "mutation",
          "path": "/sign-in",
          "method": "POST",
          "use": [
            {
              "name": "AuthFeatureProcedure"
            }
          ],
          "$Infer": {},
          "bodySchema": {
            "type": "object",
            "properties": {
              "email": {
                "type": "string",
                "format": "email"
              }
            },
            "required": [
              "email"
            ],
            "additionalProperties": false
          }
        },
        "session": {
          "path": "/session",
          "method": "GET",
          "use": [
            {
              "name": "AuthFeatureProcedure"
            }
          ],
          "$Infer": {}
        },
        "signOut": {
          "type": "mutation",
          "path": "/sign-out",
          "method": "POST",
          "use": [
            {
              "name": "AuthFeatureProcedure"
            }
          ],
          "$Infer": {}
        }
      }
    }
  },
  "docs": {
    "openapi": {
      "openapi": "3.0.0",
      "info": {
        "title": "Igniter.js Starter (Next.js)",
        "version": "1.0.0",
        "description": "A sample Next.js App built with Igniter.js"
      },
      "servers": [
        {
          "url": "http://localhost:3000/api/v1",
          "description": "Default server"
        }
      ],
      "tags": [
        {
          "name": "example"
        },
        {
          "name": "CanalMonitorado",
          "description": "Endpoints for CanalMonitorados"
        }
      ],
      "paths": {
        "/example/hello": {
          "get": {
            "summary": "hello",
            "operationId": "hello",
            "tags": [
              "example"
            ],
            "parameters": [],
            "responses": {
              "200": {
                "description": "Success",
                "content": {
                  "application/json": {
                    "schema": {}
                  }
                }
              }
            }
          }
        },
        "/canalMonitorados": {
          "get": {
            "summary": "List all CanalMonitorados",
            "operationId": "list",
            "tags": [
              "CanalMonitorado"
            ],
            "parameters": [],
            "responses": {
              "200": {
                "description": "Success",
                "content": {
                  "application/json": {
                    "schema": {}
                  }
                }
              }
            }
          },
          "post": {
            "summary": "Create a new CanalMonitorado",
            "operationId": "create",
            "tags": [
              "CanalMonitorado"
            ],
            "parameters": [],
            "requestBody": {
              "required": true,
              "content": {
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/CanalMonitoradoCreateBody"
                  }
                }
              }
            },
            "responses": {
              "200": {
                "description": "Success",
                "content": {
                  "application/json": {
                    "schema": {}
                  }
                }
              }
            }
          }
        },
        "/canalMonitorados/:id": {
          "get": {
            "summary": "Get a CanalMonitorado by ID",
            "operationId": "getById",
            "tags": [
              "CanalMonitorado"
            ],
            "parameters": [
              {
                "name": "id",
                "in": "path",
                "required": true,
                "schema": {
                  "type": "string"
                }
              }
            ],
            "responses": {
              "200": {
                "description": "Success",
                "content": {
                  "application/json": {
                    "schema": {}
                  }
                }
              }
            }
          },
          "put": {
            "summary": "Update a CanalMonitorado by ID",
            "operationId": "update",
            "tags": [
              "CanalMonitorado"
            ],
            "parameters": [
              {
                "name": "id",
                "in": "path",
                "required": true,
                "schema": {
                  "type": "string"
                }
              }
            ],
            "requestBody": {
              "required": true,
              "content": {
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/CanalMonitoradoUpdateBody"
                  }
                }
              }
            },
            "responses": {
              "200": {
                "description": "Success",
                "content": {
                  "application/json": {
                    "schema": {}
                  }
                }
              }
            }
          },
          "delete": {
            "summary": "Delete a CanalMonitorado by ID",
            "operationId": "delete",
            "tags": [
              "CanalMonitorado"
            ],
            "parameters": [
              {
                "name": "id",
                "in": "path",
                "required": true,
                "schema": {
                  "type": "string"
                }
              }
            ],
            "responses": {
              "200": {
                "description": "Success",
                "content": {
                  "application/json": {
                    "schema": {}
                  }
                }
              }
            }
          }
        }
      },
      "components": {
        "schemas": {
          "CanalMonitoradoCreateBody": {
            "type": "object",
            "properties": {
              "id_externo_wa": {
                "type": "string"
              },
              "nome": {
                "type": "string"
              },
              "ativo": {
                "type": "boolean",
                "nullable": true
              },
              "createdAt": {
                "type": "string",
                "format": "date-time",
                "nullable": true
              },
              "tags": {
                "type": "string"
              },
              "mensagens": {
                "type": "string"
              },
              "alertas": {
                "type": "string"
              }
            },
            "required": [
              "id_externo_wa",
              "nome",
              "ativo",
              "createdAt",
              "tags",
              "mensagens",
              "alertas"
            ],
            "additionalProperties": false
          },
          "CanalMonitoradoUpdateBody": {
            "type": "object",
            "properties": {
              "id_externo_wa": {
                "type": "string"
              },
              "nome": {
                "type": "string"
              },
              "ativo": {
                "type": "boolean",
                "nullable": true
              },
              "createdAt": {
                "type": "string",
                "format": "date-time",
                "nullable": true
              },
              "tags": {
                "type": "string"
              },
              "mensagens": {
                "type": "string"
              },
              "alertas": {
                "type": "string"
              }
            },
            "additionalProperties": false
          }
        },
        "securitySchemes": {}
      }
    },
    "info": {
      "title": "Igniter.js Starter (Next.js)",
      "version": "1.0.0",
      "description": "A sample Next.js App built with Igniter.js"
    }
  }
} as const

export type AppRouterSchemaType = typeof AppRouterSchema
